### ISSUE TITLE
Empty screen after performing corpus conversion and clicking LingvoDoc 3.0 link 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#286] opened 2020-09-16 05:51 UTC
Scenario with screenshots can be taken from Corpus converter enhancement #258

Login as admin

Open http://83.149.198.62/dictionary/914/4/perspective/914/7/view signed in as administrator, open markup viewer,
![image](https://user-images.githubusercontent.com/59951991/93296990-10438800-f7f9-11ea-80f3-2b7d1ea2da44.png)

launch dictionary convertion,

wait for it to finish,
![image](https://user-images.githubusercontent.com/59951991/93297062-3701be80-f7f9-11ea-95ae-3d664f940f34.png)

Click on LingvoDoc 3.0 
![image](https://user-images.githubusercontent.com/59951991/93297089-48e36180-f7f9-11ea-98fe-150ffca7d873.png)

Problem: empty screen.

Workaround: refresh page

This is not a regression.
As soon as this defect is fixed we need to update selenium test test_view_lexical_view_published.py

**Comment by myrix** [comment] 2020-09-16 07:15
@nadezhday 

Tried to reproduce, failed to do that.

After clicking on Lingvodoc 3.0, for 2-3 seconds screen is partially empty, then loader animation appears, then after some time home page loads.

Console does not show any errors, shows waiting requests when screen is partially empty and during loader animation.

**Comment by nadezhday** [comment] 2020-09-16 07:35
[2020-09-16 10-29-43_lingvodoc_refreshIsNeeded.zip](https://github.com/ispras/lingvodoc-react/files/5230576/2020-09-16.10-29-43_lingvodoc_refreshIsNeeded.zip)

**Comment by myrix** [comment] 2020-09-16 07:59
![image](https://user-images.githubusercontent.com/2802467/93308968-a1bbf580-f80b-11ea-9209-a9c52a8e27e7.png)

**Comment by myrix** [comment] 2020-09-16 08:58
Fixed with a quickfix; didn't determine the root cause of a discrepancy, just fixed its effects.

**Closed by myrix** 2020-09-16 08:58 UTC
Labels: bug, frontend

**Comment by nadezhday** [comment] 2020-09-16 12:04
Verified. The problem is not reproduced.

**Comment by nadezhday** [comment] 2020-09-17 06:36
However a regression was found. Will be reported in a new issue: After clicking LingvoDoc 3.0 link we should see the dictionary list from the top. #291

**Comment by vmonakhov** [comment] 2023-02-15 15:37
Covered in tests/test_view_published_convertion.py
