### ISSUE TITLE
Sometimes Language is not loaded. Exception.

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#438] opened 2021-03-02 11:35 UTC
Our automatic tests started to Fail.
The reason is Language cannot be loaded.
Login as Julia
Open Lingvodoc creator
Click Language
Problem: Sometimes we can get in a such state that Language is never loaded.
![image](https://user-images.githubusercontent.com/59951991/109641998-7fbcf200-7b63-11eb-9d74-89167fc36d44.png)

Here is an exception.
@myrix is it helpful? Can we fix this problem?

uncaught at a at a 
 at r 
 at i 
 e@http://83.149.198.62/assets/vendor.ff966f0d.js:1:703746
_</t.prototype.queryListenerForObserver/<@http://83.149.198.62/assets/vendor.ff966f0d.js:1:5252115
_</t.prototype.broadcastQueries/</<@http://83.149.198.62/assets/vendor.ff966f0d.js:1:5258536
_</t.prototype.broadcastQueries/<@http://83.149.198.62/assets/vendor.ff966f0d.js:1:5258515
_</t.prototype.broadcastQueries@http://83.149.198.62/assets/vendor.ff966f0d.js:1:5258422
_</t.prototype.fetchQuery/M<@http://83.149.198.62/assets/vendor.ff966f0d.js:1:5251304
raven.js:55:31
    b raven.js:55
    Redux 14

**Comment by myrix** [comment] 2021-03-02 16:52
@nadezhday 
Can't reproduce, neither at http://83.149.198.62, neither locally, exception log also does not bring anything particular to mind.

I guess 'Languages' not loading means `all_locales` request fails for some reason?
![image](https://user-images.githubusercontent.com/2802467/109683579-89108380-7b90-11eb-9eac-4041063d335e.png)
If we could get info on its state, perhaps it will be useful.

Maybe troubles between browser and server, or with the server itself.

**Comment by nadezhday** [comment] 2021-03-03 10:54
@yesandv FYI

**Comment by jandrew44** [comment] 2022-03-21 15:45
Closing as not reproducible.

**Closed as completed by jandrew44** 2022-03-21 15:45 UTC
Labels: bug, regression, critical, verified, covered

**Comment by nadezhday** [comment] 2022-03-22 04:33
Closing as fixed indirectly
