### ISSUE TITLE
Improvements in Text markup dialog

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#512] opened 2021-10-26 09:43 UTC
The features are below with the steps of reproducing. A short guide about parsers' launching and files uploading was provided in #506.
Login as admin
Create a new perspective with markup.
Open it.
Import [kaz.odt](https://github.com/ispras/lingvodoc-react/files/7416864/kaz.odt)
select
![image](https://user-images.githubusercontent.com/59951991/138851886-73f80fa8-d634-493c-963f-d7b1be4cc6d7.png)

Select a word with a lot of choices ()
![image](https://user-images.githubusercontent.com/59951991/138852980-f53c273d-5f51-4474-81f6-56e91bfabd2d.png)

Problem: All buttons are not available now. In order to use them you have to scroll.
Can we improve this functionality?
![image](https://user-images.githubusercontent.com/59951991/138853209-1d2884ec-f880-4af8-a436-6db49226a6a6.png)

**Comment by jandrew44** [comment] 2022-03-04 13:51
Duplicate of #531.

**Closed as completed by jandrew44** 2022-03-04 13:51 UTC
Labels: duplicate, enhancement, verified

**Comment by nadezhday** [comment] 2022-03-05 09:34
Verified in #531
