### ISSUE TITLE
'Disable marker' is not working properly

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#392] opened 2021-01-06 04:38 UTC
Open search http://lingvodoc.ispras.ru/map_search logged in as administrator, search for string "abc" in field "Word" as substring getting 2 results:
![image](https://user-images.githubusercontent.com/2802467/103729612-e4d7e980-4ff1-11eb-92eb-98a6d1d11f0f.png)

Scroll down to the map, try to disable one of the markers by right-clicking on it and selecting 'Disable marker':
![image](https://user-images.githubusercontent.com/2802467/103729655-fa4d1380-4ff1-11eb-86a2-def785895ac9.png)

Marker disappears, but then after several seconds appears back.

**Comment by myrix** [comment] 2021-01-06 17:10
Ok, as far as I understand, fixed, disabled markers no longer re-appear back.

**Comment by nadezhday** [comment] 2021-01-11 04:45
@myrix I am not sure how it worked before BUT what I can see now:
Problem: Marker does not disappear after invoking Disable marker context command.
In addition we have duplicated commands in our context menu for each marker on the map.

![image](https://user-images.githubusercontent.com/59951991/104147085-02d09000-53de-11eb-91a3-ba0be3568a42.png)

Steps to reproduce:
Follow the instructions from the issue description.

![image](https://user-images.githubusercontent.com/59951991/104147184-5d69ec00-53de-11eb-89cd-fe79689089ee.png)

Right click+ Disable marker.
Problem: Marker is still available.
Then right on this marker or the other one.
Problem: Duplicated context commands.

**Comment by myrix** [comment] 2021-01-11 04:54
> Problem: Marker does not disappear after invoking Disable marker context command.

Tried just now, disappeared alright:
![image](https://user-images.githubusercontent.com/2802467/104148151-2a295c00-53e2-11eb-95cf-bef1047dcd7b.png)

Maybe video with steps to reproduce?

**Comment by nadezhday** [comment] 2021-01-11 05:21
http://83.149.198.62/map_search

Backend:2.1.1+1310-1bd4d3e0-2021.01.11-04:34+modified-2021.01.11-04:44
Frontend:98020cae-418-staging-server

Uncaught TypeError: this._map is null
    _hideContextMenu leaflet.contextmenu.js:593
    fire leaflet-src.js:588
    _hide leaflet.contextmenu.js:418
    _createEventHandler leaflet.contextmenu.js:349
    a leaflet-src.js:2231
    d raven.js:393
    
[2021-01-11 08-13-45_disableMarker.zip](https://github.com/ispras/lingvodoc-react/files/5794083/2021-01-11.08-13-45_disableMarker.zip)

**Comment by myrix** [comment] 2021-01-11 05:40
Ok, it appears this bug is intermittent. Sometimes marker disappears as expected, sometimes it does not and we have this error:
![image](https://user-images.githubusercontent.com/2802467/104149645-1bde3e80-53e8-11eb-9c3d-c2fd4a863a6e.png)

Both on http://lingvodoc.ispras.ru/map_search and http://83.149.198.62/map_search, both in Chrome and Firefox.

@nadezhday also encountered another error:

```
Uncaught TypeError: Cannot read property 'contextmenu' of null
    at n._hideContextMenu (leaflet.contextmenu.js:593)
    at n.fire (leaflet-src.js:588)
    at n._hide (leaflet.contextmenu.js:418)
    at a (leaflet-src.js:2231)
    at HTMLDivElement.a (leaflet-src.js:2255)
    at HTMLDivElement.d (raven.js:393)
```

**Comment by nadezhday** [comment] 2021-01-19 05:19
Video attached:

[2021-01-19 08-14-37.zip](https://github.com/ispras/lingvodoc-react/files/5833778/2021-01-19.08-14-37.zip)

Open http://83.149.198.62/map_search
Search for: 123
Try to disable markers one by one.
Problem: One of the markers can be disabled only after invoking Disable marker twice.
![image](https://user-images.githubusercontent.com/59951991/104991141-1c518780-5a2f-11eb-809a-d02a11d38de9.png)

**Comment by jandrew44** [comment] 2021-10-20 12:26
Well, in this case you have 4 markers actually(because of 4 search results).
The problem is two of them are placed on each other, that's why it makes illusion of failure.

**Comment by nadezhday** [comment] 2021-10-25 04:43
Closing.

**Closed as completed** 2021-10-26 11:52 UTC
Labels: bug, frontend, verified, covered

**Comment by vmonakhov** [comment] 2023-02-15 14:55
Covered in tests/test_tools_search_03.py
