### ISSUE TITLE
Compute: Failed to compute analysis

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#624] opened 2022-02-18 10:55 UTC
YNormanskaya:
http://lingvodoc.ispras.ru/dictionary/4181/1/perspective/4181/2/edit
Cognate suggestions
Unselect Only for orphans option
Compute

Problem: 
![image](https://user-images.githubusercontent.com/59951991/154668800-ba561ecd-8ffd-4e5e-abc9-96052754d87b.png)

![image](https://user-images.githubusercontent.com/59951991/154668878-48ffbf0e-e1cf-4200-bdc5-4bd077caee2c.png)

@myrix, @al-indigo FYI

In my case I used http://83.149.198.62/dictionary/4181/1/perspective/4181/2/edit

**Comment by nadezhday** [comment] 2022-02-18 11:02
If we use  http://83.149.198.62/dictionary/4181/1/perspective/4181/2/edit
Computing... process never stops (waiting for 15 mins).

**Comment by myrix** [comment] 2022-02-19 23:01
With /dictionary/4181/1/perspective/4181/2/edit works as intended, after computing for 37 minutes computes successfully and displays computed suggestions.

With /dictionary/418/3/perspective/418/4/edit the error is in the liboslon.so analysis library:
```
Thread 17 "python3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb5b16700 (LWP 2587670)]
0x00007fffb66a8fcc in Segmentizer::GetNext(bool) () from /lib/liboslon.so
(gdb) bt
#0  0x00007fffb66a8fcc in Segmentizer::GetNext(bool) () from /lib/liboslon.so
#1  0x00007fffb66b28a2 in Dictionary::TranscribeWord(wchar_t*&) () from /lib/liboslon.so
#2  0x00007fffb66b2ba3 in Dictionary::GetOrigIPAAndTranslation(Parser&, wchar_t*&, wchar_t*&, wchar_t*&, bool, wchar_t*&, wchar_t*&, wchar_t*&, wchar_t*&, wchar_t*&) () from /lib/liboslon.so
#3  0x00007fffb66b3456 in Comparison::Input(wchar_t*, bool, int, int, int) () from /lib/liboslon.so
#4  0x00007fffb66a1667 in GuessCognates_GetAllOutput () from /lib/liboslon.so
```

**Comment by nadezhday** [comment] 2022-02-21 04:46
@myrix , @al-indigo What should we do with this?

**Comment by myrix** [comment] 2022-02-21 05:29
If there is no way for Mikhail to get to fix it in his library, I would say label 'wontfix' and close it.

**Comment by nadezhday** [comment] 2022-02-21 08:32
Should we report a specific Error message? So we will able to identify that Compute is not completed because of library issue.

**Comment by myrix** [comment] 2022-02-21 09:07
> Should we report a specific Error message? So we will able to identify that Compute is not completed because of library issue.

I'm not sure we can do that, don't know if at the frontend side in the browser there is a way to distinguish error due to library issue as opposed to some other reason. Will try to look into it.

**Comment by nadezhday** [comment] 2022-02-21 12:13
@myrix  are we using this library?
https://github.com/neoakut/lingvodoc-ext-oslon

**Comment by myrix** [comment] 2022-02-21 17:04
> @myrix are we using this library? https://github.com/neoakut/lingvodoc-ext-oslon

Yeah, this library, though not exactly it but slightly modified version https://github.com/ispras/lingvodoc-ext-oslon, a single difference being correction sidestepping the error from #571.

**Comment by myrix** [comment] 2022-02-22 18:33
Slightly changed error message, closing for now with 'wontfix'.

**Closed as completed by myrix** 2022-02-22 18:33 UTC
Labels: bug, wontfix, critical, verified, wontcovered

**Comment by nadezhday** [comment] 2022-03-22 09:49
That is a pity.
